services:
  - type: web
    name: groq-assistant
    runtime: python
    repo: https://github.com/v75eur/assistant
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GROQ_API_KEY_1
        sync: false
      - key: FB_PAGE_TOKEN
        sync: false
      - key: FB_PAGE_ID
        sync: false
      - key: WHATSAPP_NUMBER
        sync: false
